### ISSUE TITLE
[Feature Request] 添加的区块都是ts的文件，如何添加js的文件？

### ISSUE THREAD

**Issue by Plortinus** [umijs/umi-ui#16]
现在通过UI界面添加的区块都是ts文件，如何通过界面加js的区块文件？

**Comment by ycjcl868** [comment]
有一个开关，『使用 TypeScript』关闭即可

**Comment by Plortinus** [comment]
> 有一个开关，『使用 TypeScript』，这里弄了个智能检测，判断是 TS 项目就给默认掉了。

我用umi创建项目的时候选的是JavaScript，你说的这个开关在哪里找呢？

**Comment by Plortinus** [comment]
看了源码：
`  if (process.env.DETECT_LANGUAGE) {
    return process.env.DETECT_LANGUAGE;
  }`
我在根目录的.env文件里添加了`DETECT_LANGUAGE=JavaScript`就自动转成jsx了
