### ISSUE TITLE
添加模板失败

### ISSUE THREAD

**Issue by jm200210** [umijs/umi-ui#35]
按以下流程进行操作：
1、进入目录后，执行命令：$ yarn create @umijs/umi-app
2、$ yarn install
3、修改配置
默认的脚手架内置了 @umijs/preset-react，包含布局、权限、国际化、dva、简易数据流等常用功能。比如想要 ant-design-pro 的布局，编辑 .umirc.ts 配置 layout: {}，

import { defineConfig } from 'umi';

export default defineConfig({
+ layout: {},
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
});

4、yarn add @umijs/preset-ui
5、yarn add @umijs/preset-react
6、然后运行yarn start，进行模板添加，添加空白模板。出现错误提示：
⚓  Start git fetch
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git pull
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git pull
Already up to date.
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git pull
Already up to date.
🎉  Success git pull

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:\Users\Administrator\.umi\blocks\github.com\ant-design\pro-blocks\EmptyPage\src\index.less

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:\Users\Administrator\.umi\blocks\github.com\ant-design\pro-blocks\EmptyPage\src\index.less

🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\Administrator\.umi\blocks\github.com\ant-design\pro-blocks\EmptyPage\src\index.less
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout master
Your branch is up to date with 'origin/master'.
Already on 'master'
🎉  Success git checkout master

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:\Users\Administrator\.umi\blocks\github.com\ant-design\pro-blocks\EmptyPage\src\index.less

🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\Administrator\.umi\blocks\github.com\ant-design\pro-blocks\EmptyPage\src\index.less

但很明显， C:\Users\Administrator\.umi\blocks\github.com\ant-design\pro-blocks\EmptyPage\src\index.less是存在的。
![image](https://user-images.githubusercontent.com/50350622/76698558-62d3a880-66df-11ea-91d2-aba156fc307c.png)

**Comment by ycjcl868** [comment]
版本号多少

**Comment by jm200210** [comment]
现在新增空白页没问题了，但我试了一下新增个人中心，还是不行，最后的错误提示为：
success Saved 0 new dependencies.
√ 📦  Install additional dependencies @ant-design/icons@^4.0.0-alpha.19,classnames@^2.2.6,dva@^2.4.0,moment@^2.24.0,numeral@^2.0.6,react-router@^4.3.1,redux@^4.0.1,umi-request@^1.0.0 with tyarn --registry https://registry.npm.taobao.org
📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi/blocks/github.com/ant-design/pro-blocks/AccountCenter/src/components


🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi/blocks/github.com/ant-design/pro-blocks/AccountCenter/src/components

![image](https://user-images.githubusercontent.com/50350622/76815822-a4786680-6839-11ea-992c-bc946d2619e8.png)


另外：新增空白页虽然成功，但在空白页上新增区块，却还是不行，开始出现这个问题（我是新增表单-高级搜索）：
![image](https://user-images.githubusercontent.com/50350622/76815931-ea352f00-6839-11ea-8761-8b51707d7c7f.png)

不知道为什么提示这个目录不存在，难道要我先写什么代码吗？还是有什么别的要求。不过我手工创建了这个目录，于是出现这个提示：
![image](https://user-images.githubusercontent.com/50350622/76816023-1cdf2780-683a-11ea-8e09-7735e3ffcac1.png)

总结一下，这里有二个问题：
1、新增模板还是报错。
2、新增区块报错。

**Comment by ycjcl868** [comment]
怎么到了 `.umi`？

**Comment by jm200210** [comment]
我也不知道，从如至终，我都是按你们说明上做的，没多做一步，也没自己写一个字母。按我上面说的步骤，这些问题是必现的。

**Comment by jm200210** [comment]
> 怎么到了 `.umi`？

不知道这个问题有解决么？为什么新增区块的时候会去获取.umi目录？
