### ISSUE TITLE
添加查询表格模板报错

### ISSUE THREAD

**Issue by abcnny** [umijs/umi-ui#39]
## What happens?

用的ant design pro中自带的umi，版本3.0.0，@umijs/preset-ui 版本2.0.9，用umi dev启动后，添加查询表格模板报错，日志信息如下

⚓  Start git fetch
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi/blocks/github.com/ant-design/pro-blocks/ListTableList/src/components

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi/blocks/github.com/ant-design/pro-blocks/ListTableList/src/components

🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi/blocks/github.com/ant-design/pro-blocks/ListTableList/src/components
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi/blocks/github.com/ant-design/pro-blocks/ListTableList/src/components

🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/Administrator/.umi/blocks/github.com/ant-design/pro-blocks/ListTableList/src/components

## 相关环境信息

- **Umi 版本**：
umi3.0.0
- **Node 版本**：
v12.16.1
- **操作系统**：
win10

**Comment by ycjcl868** [comment]
复现 demo

**Comment by aspirantzhang** [comment]
跟#35 应该一样，实测win10上添加区块普遍存在问题：
```
Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/aspirantzhang/.umi3/blocks/github.com/ant-design/pro-blocks/ListBasicList/src/components

⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/aspirantzhang/.umi3/blocks/github.com/ant-design/pro-blocks/ListBasicList/src/components


🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/aspirantzhang/.umi3/blocks/github.com/ant-design/pro-blocks/ListBasicList/src/components
⚓  Start git fetch
🎉  Success git fetch

⚓  Start git checkout umi@3
Your branch is up to date with 'origin/umi@3'.
Already on 'umi@3'
🎉  Success git checkout umi@3

⚓  Start git pull
Already up to date.
🎉  Success git pull

📦  Start generate files
Faild generate files: Trying to copy from a source that does not exist: C:/Users/aspirantzhang/.umi3/blocks/github.com/ant-design/pro-blocks/ListBasicList/src/components


🚧  Execute task error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/aspirantzhang/.umi3/blocks/github.com/ant-design/pro-blocks/ListBasicList/src/components
```
同时命令行报错
```
Execute task error Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/aspirantzhang/.umi3/blocks/github.com/ant-design/pro-blocks/ListBasicList/src/components
    at E:\www\ant\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:109:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (E:\www\ant\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:50:103)
    at _throw (E:\www\ant\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:52:291)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[Asset Error] Error: AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:/Users/aspirantzhang/.umi3/blocks/github.com/ant-design/pro-blocks/ListBasicList/src/components
    at E:\www\ant\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:109:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (E:\www\ant\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:50:103)
    at _throw (E:\www\ant\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\run_generator.js:52:291)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
