### ISSUE TITLE
点击气泡没有反应

### ISSUE THREAD

**Issue by abcnny** [umijs/umi-ui#41]
## What happens?

 npx @umijs/create-umi-app
npm install
npm install @umijs/preset-ui -D
执行完上面命令之后，
 运行umi dev，页面上的气泡点击后一直处于加载状态，且报了以下错误 ，
App running at:
  - Local:   http://localhost:8001 (copied to clipboard)
  - Network: http://192.168.137.1:8001
GotError [RequestError]: connect ECONNREFUSED 127.0.0.1:8002
    at ClientRequest.<anonymous> (D:\job\lxspace\umiui\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.origin.emit (D:\job\lxspace\umiui\node_modules\@szmarczak\http-timer\source\index.js:37:11)    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'RequestError',
  code: 'ECONNREFUSED',
  host: 'localhost:8002',
  hostname: 'localhost',
  method: 'GET',
  path: '/',
  socketPath: undefined,
  protocol: 'http:',
  url: 'http://localhost:8002/',
  gotOptions: {
    path: '/',
    protocol: 'http:',
    slashes: true,
    auth: null,
    host: 'localhost:8002',
    port: '8002',
    hostname: 'localhost',
    hash: null,
    search: null,
    query: null,
    pathname: '/',
    href: 'http://localhost:8002/',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET',
    forceRefresh: true
  }
}
GotError [RequestError]: connect ECONNREFUSED 127.0.0.1:8002
    at ClientRequest.<anonymous> (D:\job\lxspace\umiui\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.origin.emit (D:\job\lxspace\umiui\node_modules\@szmarczak\http-timer\source\index.js:37:11)    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'RequestError',
  code: 'ECONNREFUSED',
  host: 'localhost:8002',
  hostname: 'localhost',
  method: 'GET',
  path: '/',
  socketPath: undefined,
  protocol: 'http:',
  url: 'http://localhost:8002/',
  gotOptions: {
    path: '/',
    protocol: 'http:',
    slashes: true,
    auth: null,
    host: 'localhost:8002',
    port: '8002',
    hostname: 'localhost',
    hash: null,
    search: null,
    query: null,
    pathname: '/',
    href: 'http://localhost:8002/',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET',
    forceRefresh: true
  }
}

贴一下package.json
{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,less,md,json}": [
      "prettier --write"
    ],
    "*.ts?(x)": [
      "prettier --parser=typescript --write"
    ]
  },
  "dependencies": {
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.0.14",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.0.14",
    "yorkie": "^2.0.0"
  },
  "devDependencies": {
    "@umijs/preset-ui": "^2.1.0"
  }
}

- **Umi Version**:
3.0.14
- **Node Version**:
v12.16.1
- **Platform**:
win10

**Comment by zhongsimeng** [comment]
修改.env文件，PORT=8002，未出现以上报错信息。
但页面上的气泡点击加载后黑屏，控制台报错，
Uncaught SyntaxError: Unexpected token '<'

**Comment by ycjcl868** [comment]
应该修复了，重装模块
