### ISSUE TITLE
体验反馈

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi-ui#5]
- [x] dev 启动 mini 时，Umi UI 地址与 dev 地址易混淆 https://github.com/umijs/ui/pull/6

![image](https://user-images.githubusercontent.com/13595509/73529988-9b326680-4452-11ea-9baa-632c0da9d595.png)

## 资产

- [ ]  三列排列空出一个

![https://user-images.githubusercontent.com/13595509/73436754-11b56280-4386-11ea-9b63-73f614e528e0.png](https://user-images.githubusercontent.com/13595509/73436754-11b56280-4386-11ea-9b63-73f614e528e0.png)

- [ ]  git clone 用的 http 协议，有时候会走代理，导致 clone 失败

![https://user-images.githubusercontent.com/13595509/73436472-8b008580-4385-11ea-92e7-94650de7ef83.png](https://user-images.githubusercontent.com/13595509/73436472-8b008580-4385-11ea-92e7-94650de7ef83.png)

- [ ]  加载过慢，不停地 loading

![https://user-images.githubusercontent.com/13595509/73436279-2f35fc80-4385-11ea-99d0-4e981bf17ecb.png](https://user-images.githubusercontent.com/13595509/73436279-2f35fc80-4385-11ea-99d0-4e981bf17ecb.png)

- [x]  资产图片预览

![https://user-images.githubusercontent.com/13595509/73435998-a74ff280-4384-11ea-9fac-4289836ed093.png](https://user-images.githubusercontent.com/13595509/73435998-a74ff280-4384-11ea-9fac-4289836ed093.png)

**Comment by LamTech** [comment]
same problem here!
