### ISSUE TITLE
[Feature Request] 增加一个按钮，快速预览代码

### ISSUE THREAD

**Issue by stfenjobs** [umijs/umi-ui#50]
建议在这里增加一个按钮。， 可以快速预览代码（可以在新窗口中 打开github对应组件的页面）

![image](https://user-images.githubusercontent.com/6580897/78245641-68702180-751a-11ea-8648-6726207010f4.png)

有时候只想看看对应代码，好从中复制一段过来用

**Comment by ycjcl868** [comment]
这个在 Umi Community  区块数据里有，https://cdn.jsdelivr.net/npm/@umijs/assets-umi@1.0.0/blocks.json

没做展示

**Comment by ycjcl868** [comment]
并且这个预览代码，不止 tsx 代码、还有 less ，不建议展示，更好的方式是帮项目添加
