### ISSUE TITLE
[Feature Request]  请默认移除 【国际化】

### ISSUE THREAD

**Issue by stfenjobs** [umijs/umi-ui#51]
umi3

![image](https://user-images.githubusercontent.com/6580897/78247150-f3521b80-751c-11ea-89f7-508362434065.png)

添加模板的时候， 他默认没有选中， 所以有些模块我安装后 会报错  如：https://github.com/umijs/umi-ui/issues/49

建议 ，默认 就选中这个

当用户 切换 这个按钮的时候， 后台 先判断 用户是否 启用了国际化， 如果没有启用，就要求用户先启用

**Comment by warmhug** [comment]
能否支持在 生成的 html 里插入、国际化文案 所在元素的 editable 属性，方便直接编辑文案、并更新到代码中？
